/**
 * AUTO-GENERATED SECURITY REPORT
 * Generated by run_security_scan.js
 */
export const SECURITY_REPORT = {
  "sca": {
    "status": "WARN",
    "details": "Vulnerabilities detected"
  },
  "secrets": {
    "status": "FAIL",
    "details": "Exposed key in: .env"
  },
  "rls": {
    "status": "FAIL",
    "details": "Missing RLS in: supabase-rag-setup.sql"
  },
  "sast": {
    "status": "PASS",
    "details": "Clean scan"
  },
  "timestamp": "2026-05-13T23:58:39.056Z"
};

export const ISSUE_LOG = [
  {
    "id": "VMS-OPS-001",
    "title": "Gemini API 404 Connection Error",
    "status": "RESOLVED",
    "severity": "CRITICAL",
    "detectedAt": "2026-05-11T02:30:00Z",
    "resolvedAt": "2026-05-11T03:45:00Z",
    "remediation": "Updated model name to gemini-embedding-2 and gemini-3.1-pro-preview"
  },
  {
    "id": "VMS-SEC-KEY-059",
    "title": "Exposed Gemini API Key",
    "status": "OPEN",
    "severity": "CRITICAL",
    "detectedAt": "2026-05-13T23:58:40.059Z",
    "remediation": "Revoke key and move to encrypted vault"
  },
  {
    "id": "VMS-OPS-RLS-060",
    "title": "Unprotected Database Tables",
    "status": "OPEN",
    "severity": "HIGH",
    "detectedAt": "2026-05-13T23:58:40.060Z",
    "remediation": "Apply ENABLE ROW LEVEL SECURITY to all tables"
  }
];
